# @package _global_

dataset_name: zju_377_mono

dataset:
  name: zjumocap # dummy_dataset # zjumocap
  root_dir: "./data/ZJUMoCap"
  subject: CoreView_377
  refine: false

  train_views: ['1', '2']
  val_views: ['5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23']
  test_views:
    view: ${dataset.val_views}
    video: ['5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23']
    all: []
  predict_views: ['3', '4']

  train_frames: [ 0, 570, 1 ]
  val_frames: [ 0, 1, 1 ]
  test_frames:
    view: [0, 570, 30]
    video: [0, 570, 1]
    all: [0, 570, 1]
  predict_frames: [0, 0, 1]

  img_hw:
    - 512
    - 512

  lanczos: false
  resolution: -1
  white_background: false
  data_device: cuda
  eval: false
  freeview: false