# @package _global_

dataset_name: zju_001_mono

dataset:
  name: mydataset #  dummy_dataset
  root_dir: "./data/ZJUMoCap"
  subject: CoreView_001
  refine: false

  train_views: ['1']
  val_views: ['1']
  test_views:
    view: ${dataset.val_views}
    video: ['12']
    all: []
  predict_views: ['1']

  train_frames: [ 0, 1700, 1 ]
  val_frames: [ 1701, 1702, 1 ]
  test_frames:
    view: [0, 540, 30]
    video: [0, 540, 1]
    all: [0, 540, 1]
  predict_frames: [0, 0, 1]

  img_hw:
    - 512
    - 512

  lanczos: false
  resolution: -1
  white_background: false
  data_device: cuda
  eval: false